### ISSUE TITLE
Mod Name potential incompatibility

### ISSUE THREAD

**Issue by NilaierMusic** [ThePotato97/ScanErrorFix#1]
Consider changing dll name from `ScanFix.dll` into `scanForItemsFix.dll` or `ScanErrorFix.dll`, since [ScanFix](https://thunderstore.io/c/lethal-company/p/Nebulaetrix/ScanFix/) mod already uses `ScanFix.dll` as their dll name for their patches for in-terminal scanner.

Sincerely,
Replace or Skip Files Window
![explorer_wgzYUMkUYv](https://github.com/ThePotato97/ScanErrorFix/assets/86863646/447bef7e-103b-462b-bf5e-884040e5bd18)

**Comment by ThePotato97** [comment]
doesn't that mod already change the behavior of scan?

**Comment by NilaierMusic** [comment]
> doesn't that mod already change the behavior of scan?

Well, it does, but it doesn't fix the issue that your mod tries to fix, hence why together they would be more preferred.

**Comment by ThePotato97** [comment]
Resolved by commit 83fd7c4

Changed the assembly name to `ThePotato-scanFixForItemsFix` to align with the Thunderstore naming convention.
